name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  xcode_16_4:
    runs-on: macos-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.4.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests --enable-code-coverage --enable-experimental-prebuilts
      - name: Test
        run: swift test --skip-build --enable-code-coverage
      - name: Gather code coverage
        run: xcrun llvm-cov export -format="lcov" .build/debug/swift-case-projectionPackageTests.xctest/Contents/MacOS/swift-case-projectionPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov
      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage_report.lcov

  xcode_26:
    runs-on: macos-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.0.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build

  linux_swift_6_1:
    runs-on: ubuntu-latest
    container: swift:6.1.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests --enable-experimental-prebuilts
      - name: Test
        run: swift test --skip-build

  linux_swift_6_2:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-6.2-noble
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build
